{"name": "Проверка неуспешного получения заказа при указании несущетвующего id", "status": "passed", "description": "Негативный сценарий тестирования ручки \"Получить заказ по его номеру\" GET /api/v1/orders/track.Запрос с несуществующим заказом возвращает соответсвующую ошибку.", "start": 1709998111368, "stop": 1709998111432, "uuid": "927c29c1-035a-42d4-b0d7-c45a2beaba30", "historyId": "459ac23a81d13c69579f2d105d297fef", "testCaseId": "459ac23a81d13c69579f2d105d297fef", "fullName": "tests.test_get_order_by_id.TestGetOrderById#test_get_order_no_exist_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_id"}, {"name": "subSuite", "value": "TestGetOrderById"}, {"name": "host", "value": "Elmiras-MacBook-Pro-3.local"}, {"name": "thread", "value": "48166-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_id"}]}